In [5]:
import numpy as np
a =np.array([1,2,3])
b =np.array((3,2,3))
print(a)
print(b)

[1 2 3]
[3 2 3]


In [1]:
a =''
b =a.split()
type(b)

list

In [1]:
import numpy as np
print(np.__version__)

1.18.2


In [7]:
b[1]=4
print(b)

[3 4 3]


In [6]:
c =np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
type(c)

numpy.ndarray

In [14]:
c[1]

array([4, 5, 6])

In [15]:
c[0]

array([1, 2, 3])

In [8]:
c[:0]

array([], shape=(0, 3), dtype=int32)

In [20]:
a[0:]

array([1, 2, 3])

In [10]:
a[0:3]

array([1, 2, 3])

In [21]:
a =np.zeros((3,3))#np.zeros((rows,coloum))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
#np.arange(starting nu,ending num,diffrrent)
a =np.arange(10,34,2)
print(a)

[10 12 14 16 18 20 22 24 26 28 30 32]


In [25]:
#np.linspace(starting num,ending nu,nu of you space)
b =np.linspace(1,2,15)
print(b)

[1.         1.07142857 1.14285714 1.21428571 1.28571429 1.35714286
 1.42857143 1.5        1.57142857 1.64285714 1.71428571 1.78571429
 1.85714286 1.92857143 2.        ]


In [13]:
#np.full((rows,coloum),element)
c =np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
d =np.random.random((3,3))
d

array([[0.28926059, 0.76301725, 0.92359537],
       [0.15519355, 0.09801453, 0.56654688],
       [0.46476566, 0.44766268, 0.36735347]])

In [15]:
a =np.array( [[1,2,3],[4,5,6]])
print(a)
#shape fun use for a row nu and col num
print(a.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)


In [23]:
a =np.array( [[1,2,3],[4,5,6]])
a.shape =(3,2)
#print(a.shape[1])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
import numpy as np
a =np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a.shape)
a.shape =(5,2)
print(a.shape[1])
print(a.shape[0])
print(a)

(2, 5)
2
5
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [8]:
import numpy as np
a =np.array( [[1,2,3,4],[5,6,7,8]] )
print(a.shape)
print(a.ndim)
a.shape =(4,2)
print(a)


(2, 4)
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2]:
#np.range(number of point needed)
#will place the num between 0 till thatnumber
import numpy as np
a =np.array( [[1,2,3,4],[5,6,7,8]] )
print(a)
a =np.arange(8)
print(a)

[[1 2 3 4]
 [5 6 7 8]]
[0 1 2 3 4 5 6 7]


In [33]:
import numpy as np
a =np.array( [[1,2,3],[4,5,6]])
print(a)
a.size

[[1 2 3]
 [4 5 6]]


6

In [ ]:
a.size

In [3]:
import numpy as np
a =np.arange(24)
print(a.size)
print(a)
print(a.dtype)

24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
int32


In [12]:
b =np.linspace(5,10,14)
print(b)
print(b.dtype)

[ 5.          5.38461538  5.76923077  6.15384615  6.53846154  6.92307692
  7.30769231  7.69230769  8.07692308  8.46153846  8.84615385  9.23076923
  9.61538462 10.        ]
float64


In [37]:
a =np.array([5,6])
np.sum(a)

11

In [7]:
a =np.array([2,3,4])
b =np.array([2,1,6])


print(a)
print("\n")
print(b)
print("\n")

print(np.subtract(a,b))
print(np.add(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.equal(a,b))
print(np.array_equal(a,b))
print(np.sum([a,b],axis=1))# base on the col
print(np.sum([a,b],axis=0))#bas eon the row

[2 3 4]


[2 1 6]


[ 0  2 -2]
[ 4  4 10]
[1.         3.         0.66666667]
[ 4  3 24]
[0.69314718 1.09861229 1.38629436]
[ 0.90929743  0.14112001 -0.7568025 ]
[-0.41614684 -0.9899925  -0.65364362]
[ True False False]
False
[9 9]
[ 4  4 10]


In [49]:
a =np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

21
1
6
3.5
1.707825127659933
3.5
[[1. 1.]
 [1. 1.]]


In [7]:
#array brodcasting
import numpy as np
a =np.array([[1,2,3],[4,5,6],[1,2,3]])
b =np.array([1,2,3])
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [5 7 9]
 [2 4 6]]
[[0 0 0]
 [3 3 3]
 [0 0 0]]
[[ 1  4  9]
 [ 4 10 18]
 [ 1  4  9]]
[[1.  1.  1. ]
 [4.  2.5 2. ]
 [1.  1.  1. ]]


In [19]:
str1= "monty python"
print(str1)
print(str1[5:12])
print(str1[-12:-6])

monty python
 python
monty 


In [10]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print(a)


print(a[:1])
print(a[:2])
print(a[1:])
print(a[2:])
print(a[0:])

print(a[:,1:])

print(a[:,:1])
print(a[1:,:3])
print(a[:2,:3])




[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1]
 [4]
 [7]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [39]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a)
print("\n")
print(a[0])
print("\n")
print(a[:1])
print('\n')
print(a[:1,2:])
print("\n")
print(a[:2,1:])
print("\n")
print(a[:,1:])
print(a[2,1:])
print(a[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3]


[[1 2 3]]


[[3]]


[[2 3]
 [5 6]]


[[2 3]
 [5 6]
 [8 9]]
[8 9]
5


In [1]:
import numpy as np
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[2,4,5],[1,3,3]])
print(a)
print(b)
import numpy as np
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[2,4,5],[1,3,3]])
print(a)
print(b)
print("\n horizontal concat")
print(np.concatenate((a,b),axis=0))
print("\n horizontal concat")
print(np.concatenate((a,b),axis=0))
print("\n vartical concat")
print(np.concatenate((a,b),axis=1))
print("\n row way")
print(np.stack((a,b),axis=0))
print("\n coloum way")
print(np.stack((a,b),axis=1))
print("\n horizontal concat")
print(np.concatenate((a,b),axis=0))
print("\n vartical concat")
print(np.concatenate((a,b),axis=1))
print("\n row way")
print(np.stack((a,b),axis=0))
print("\n coloum way")
print(np.stack((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[2 4 5]
 [1 3 3]]

 horizontal concat
[[1 2 3]
 [4 5 6]
 [2 4 5]
 [1 3 3]]

 vartical concat
[[1 2 3 2 4 5]
 [4 5 6 1 3 3]]

 row way
[[[1 2 3]
  [4 5 6]]

 [[2 4 5]
  [1 3 3]]]

 coloum way
[[[1 2 3]
  [2 4 5]]

 [[4 5 6]
  [1 3 3]]]


In [4]:
import numpy as np
a =np.array([[1,2,3],[4,5,6]])
b =np.array([[2,4,5],[1,3,3]])
print(a)
print(b)
print("\n row way")
print(np.stack((a,b),axis=0))
print("\n coloum way")
print(np.stack((a,b),axis=1))
print("\n horizontal stack")
print(np.hstack((a,b)))
print("\n horizontal concat")
print(np.concatenate((a,b),axis=0))
print("\n vartical stack")
print(np.hstack((a,b)))
print("\n vartical concat")
print(np.concatenate((a,b),axis=1))

[[1 2 3]
 [4 5 6]]
[[2 4 5]
 [1 3 3]]

 row way
[[[1 2 3]
  [4 5 6]]

 [[2 4 5]
  [1 3 3]]]

 coloum way
[[[1 2 3]
  [2 4 5]]

 [[4 5 6]
  [1 3 3]]]

 horizontal stack
[[1 2 3 2 4 5]
 [4 5 6 1 3 3]]

 horizontal concat
[[1 2 3]
 [4 5 6]
 [2 4 5]
 [1 3 3]]

 vartical stack
[[1 2 3 2 4 5]
 [4 5 6 1 3 3]]

 vartical concat
[[1 2 3 2 4 5]
 [4 5 6 1 3 3]]


In [7]:
print(a)
print(np.split(a,3,axis=1))

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [8]:
print(np.split(a,[1,2],axis=0))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [9]:
a[:1]

array([[1, 2, 3]])

In [10]:
a[1:2]

array([[4, 5, 6]])

In [11]:
a[2:]

array([], shape=(0, 3), dtype=int32)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
print(np.split(a,[1,2],axis=1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [14]:
a[:,:1]

array([[1],
       [4]])

In [15]:
a[:,1:2]

array([[2],
       [5]])

In [16]:
a[:,2:]

array([[3],
       [6]])

In [5]:
import numpy as np
x =np.linspace(-2,2,9)
y =np.linspace(-5,5,9)
x1,y1 =np.meshgrid(x,y)
print(x1)
print(y1)

[[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]
 [-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]]
[[-5.   -5.   -5.   -5.   -5.   -5.   -5.   -5.   -5.  ]
 [-3.75 -3.75 -3.75 -3.75 -3.75 -3.75 -3.75 -3.75 -3.75]
 [-2.5  -2.5  -2.5  -2.5  -2.5  -2.5  -2.5  -2.5  -2.5 ]
 [-1.25 -1.25 -1.25 -1.25 -1.25 -1.25 -1.25 -1.25 -1.25]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25]
 [ 2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5 ]
 [ 3.75  3.75  3.75  3.75  3.75  3.75  3.75  3.75  3.75]
 [ 5.    5.    5.    5.    5.    5.    5.    5.    5.  ]]
